[project]
name = "mcp-memory"
version = "0.1.0"
description = "MCP Memory based on ChromaDB"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["mcp[cli]>=1.7.1"]

[tool.pyright]
venvPath = "."
venv = ".venv"
